scalar Upload @scalar(class: "App\\GraphQL\\Scalars\\Upload")

type Query {
    schedules: [Schedule!]! @all
    schedule(id: ID! @eq): Schedule @find
}

type Mutation {
    createSchedule(
        day: String!
        start_time: String!
        end_time: String!
        room: String!
        instructor: String!
    ): Schedule! @create(model: "App\\Models\\Schedule")

    updateSchedule(
        id: ID!
        day: String
        start_time: String
        end_time: String
        room: String
        instructor: String
    ): Schedule @update(model: "App\\Models\\Schedule")

    deleteSchedule(id: ID! @eq): Schedule @delete(model: "App\\Models\\Schedule")

    assignStudentToSchedule(
    id: ID!
    schedule_id: ID
    ): Student! @update(model: "App\\Models\\User")

   importStudentsCsv(file: Upload!): ImportResult!
        @field(resolver: "App\\GraphQL\\Mutations\\ImportStudentsCsv")
}

type Schedule {
    id: ID!
    day: String!
    start_time: String!
    end_time: String!
    room: String!
    instructor: String!
    students: [Student!]! @hasMany
    created_at: String
    updated_at: String
}

type Student @model(class: "App\\Models\\User") {
    id: ID!
    name: String!
    email: String!
    schedule: Schedule @belongsTo
}

type ImportResult {
    message: String!
}